name: data-glasses
version: 0.1.0.0
github: "githubuser/data-glasses"
license: BSD3
author: "Callum Lowcay"
maintainer: "cwslowcay@gmail.com"
copyright: "2021 Callum Lowcay"

extra-source-files:
  - README.md
  - ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/CLowcay/data-glasses#readme>

dependencies:
  - aeson
  - base >= 4.7 && < 5
  - bytestring
  - containers
  - hashable
  - megaparsec
  - scientific
  - text
  - unordered-containers

library:
  source-dirs: src

executables:
  dagl:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - data-glasses

tests:
  data-glasses-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - data-glasses
      - hspec
